### ISSUE TITLE
application does not start trying to access the printers

### ISSUE THREAD

**Issue by ccronemberger** [alm-tools/alm#122]
Here is the generated output:

$ alm
```
DASHBOARD: http://localhost:4444
Globbing error: { [Error: EPERM: operation not permitted, scandir 'C:\Users\ccron\Ambiente de Impressão']
  errno: -4048,
  code: 'EPERM',
  syscall: 'scandir',
  path: 'C:\\Users\\ccron\\Ambiente de Impressão' }
C:\Users\ccron\AppData\Roaming\npm\node_modules\alm\src\server\workers\fileListing\fileListingWorker.js:106
                var list = newList.map(function (nl) {
                                  ^

TypeError: Cannot read property 'map' of undefined
    at Glob.<anonymous> (C:\Users\ccron\AppData\Roaming\npm\node_modules\alm\src\server\workers\fileListing\fileListingWorker.js:106:35)
    at Glob.f (C:\Users\ccron\AppData\Roaming\npm\node_modules\alm\node_modules\once\once.js:17:25)
    at emitOne (events.js:77:13)
    at Glob.emit (events.js:169:7)
    at Glob._readdirError (C:\Users\ccron\AppData\Roaming\npm\node_modules\alm\node_modules\glob\glob.js:574:14)
    at C:\Users\ccron\AppData\Roaming\npm\node_modules\alm\node_modules\glob\glob.js:525:12
    at FSReqWrap.oncomplete (fs.js:82:15)
 fileListingWorker worker restarting. Don't know why it stopped with code: 1
```

**Comment by basarat** [comment]
> Here is the generated output:

you probably started it some root level (e.g. `c:\`). We glob the whole folder to provide a faster *search for file* experience. Please start at a project level folder.

Leaving it open as we should provide a better error experience here :rose:

**Comment by ccronemberger** [comment]
That is true, I was trying to run it in my home directory. Running it in a project directory it works.

**Comment by basarat** [comment]
We now report this as an error :rose: `0.3.2`

<img width="830" alt="screen shot 2016-08-05 at 2 18 23 am" src="https://cloud.githubusercontent.com/assets/874898/17409556/2348ce16-5ab3-11e6-8806-8ec46228ca13.png">
