### ISSUE TITLE
Meta Issue: Monaco

### ISSUE THREAD

**Issue by basarat** [alm-tools/alm#245]
The latest version of monaco breaks a few things. This is to track them as I discover them 

* [x] Invalid marker. Stacktrace: 

```
Uncaught (in promise) Error: invalid marker service state
    at MarkerService.changeOne (http://localhost:4444/vs/editor/editor.main.js:59645:27)
    at Object.setModelMarkers (http://localhost:4444/vs/editor/editor.main.js:80762:65)
    at performLint (webpack:///../alm/src/app/monaco/addons/linter.js?:38:23)
    at Object.setup (webpack:///../alm/src/app/monaco/addons/linter.js?:53:5)
    at eval (webpack:///../alm/src/app/monaco/editor/codeEditor.js?:183:41)
```
Reported : https://github.com/Microsoft/vscode/issues/13548 :rose:

* [x] Snippet ordering : https://github.com/alm-tools/alm/issues/219

**Comment by basarat** [comment]
Released with `2.5.0` :rose:
