### ISSUE TITLE
Testing with with a custom path into our tsconfig

### ISSUE THREAD

**Issue by Rain-io** [alm-tools/alm#461]
Hello !

I've a path shortcut in my tsconfig.json like this : 

`"compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "noImplicitAny": true,
        "baseUrl": ".",
        "paths": {
            "bmb": [
                "src/App"
            ]
        }
    },
    "compileOnSave": false,
    "exclude": [
        "node_modules"
    ]`

And when i use this shortcut into a testing file to import, it doesn't work and i have this error message :

`MOCHA STDERR: /usr/local/lib/node_modules/alm/src/server/workers/tested/runners/instrumenterCommon.js:57
        lastPositionInFile: stack.find(function (s) { return s.filePath === filePath; }).position,
                                                                                        ^

TypeError: Cannot read property 'position' of undefined
    at exports.makeTestLogPosition (/usr/local/lib/node_modules/alm/src/server/workers/tested/runners/instrumenterCommon.js:57:89)
    at Console.addToLogs (/usr/local/lib/node_modules/alm/src/server/workers/tested/runners/mochaInstrumenter.js:18:27)
    at printErrorAndExit (/usr/local/lib/node_modules/alm/node_modules/source-map-support/source-map-support.js:402:11)
    at process.emit (/usr/local/lib/node_modules/alm/node_modules/source-map-support/source-map-support.js:415:16)
    at process._fatalException (bootstrap_node.js:299:26)

/usr/local/lib/node_modules/alm/src/server/workers/tested/runners/mochaRunner.js:110
    var stats = output.stats;
                      ^

TypeError: Cannot read property 'stats' of undefined
    at parseMochaJSON (/usr/local/lib/node_modules/alm/src/server/workers/tested/runners/mochaRunner.js:110:23)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/alm/src/server/workers/tested/runners/mochaRunner.js:90:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:513:12)`

Thanks for all your work, it's great 👍

**Comment by basarat** [comment]
> Thanks for all your work

Thanks :rose: 

Can I get a sample project please :heart:

**Comment by Rain-io** [comment]
Ok clone this repo :
https://github.com/Rain-io/alm-issue-461/tree/master

So, i comment the line generating errors (the import with a ts shortcut), in the test file, to prove that everything is ok. You can de-comment it, and comment the relative import, and you will see the error.

**Comment by basarat** [comment]
Basically `ts-node/mocha` is crashing. Should provide a `tsconfig path` option for tests in `alm.json`. Will to that soonish :rose:
