### ISSUE TITLE
fileListingWorker restarting

### ISSUE THREAD

**Issue by xylifyx** [alm-tools/alm#503]
Tried out alm in the cloud shell on gcloud. It complains repeatetly about FSWatcher. I guess that
the cloud shell doesn't support that. But that should not cause alm to fail.

```
Error: watch /home/erik_martino/angular-start/node_modules/sntp/package.json ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at createFsWatchInstance (/usr/local/nvm/versions/node/v6.9.2/lib/node_modules/alm/node_mo
dules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/usr/local/nvm/versions/node/v6.9.2/lib/node_modules/alm/node_modul
es/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/usr/local/nvm/versions/node/v6.9.2/lib/node_
modules/alm/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/usr/local/nvm/versions/node/v6.9.2/lib/node_modul
es/alm/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/usr/local/nvm/versions/node/v6.9.2/lib/node_modules/alm/node_mo
dules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:123:15)
fileListingWorker worker restarting. Don't know why it stopped with code: 1
projectServiceWorker worker restarting. Don't know why it stopped with code: null
[LINT] Lint complete 282s
events.js:160
      throw er; // Unhandled 'error' event
```

**Comment by basarat** [comment]
Think you need to run this : `echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

More : http://stackoverflow.com/a/17437601/390330 /  http://stackoverflow.com/q/38845101/390330

I'm relying on `chokidar` to solve the file watching problems instead of creating my own solution :rose:
