### ISSUE TITLE
TypeError - getTopLevelModuleNames, TSLint implementations missing

### ISSUE THREAD

**Issue by alohaninja** [alm-tools/alm#555]
Getting numerous warnings about **TSLint** rules and `TypeError` using alm 2.36.4. Any ideas where these are coming from? This is a new project trying to get ALM working in - works great with simple project structure. 

```
Could not find implementations for the following rules specified in the configuration:
    label-undefined
    no-duplicate-key
    no-trailing-comma
    no-unreachable
    use-strict
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
        

{ method: 'getTopLevelModuleNames',
  message: 'Cannot read property \'kind\' of undefined',
  stack: 'TypeError: Cannot read property \'kind\' of undefined\n    at transformModule (C:\\Users\\<username>\\AppData\\Roaming\\npm\\node_modules\\alm\\src\\server\\workers\\lang\\docs\\transformers.js:323:18)\n    at C:\\Users\\<username>\\AppData\\Roaming\\npm\\node_modules\\alm\\src\\server\\workers\\lang\\docs\\transformers.js:55:27\n    at visitEachNode (C:\\Users\\<username>\\AppData\\Roaming\\npm\\node_modules\\alm\\node_modules\\typescript\\lib\\typescript.js:15008:30)\n    at Object.forEachChild (C:\\Users\\<username>\\AppData\\Roaming\\npm\\node_modules\\alm\\node_modules\\typescript\\lib\\typescript.js:15182:24)\n    at getSignificantSubItems (C:\\Users\\<username>\\AppData\\Roaming\\npm\\node_modules\\alm\\src\\server\\workers\\lang\\docs\\transformers.js:34:8)\n    at Object.transformSourceFile (C:\\Users\\<username>\\AppData\\Roaming\\npm\\node_modules\\alm\\src\\server\\workers\\lang\\docs\\transformers.js:21:20)\n    at Object.getTopLevelModuleNames (C:\\Users\\<username>\\AppData\\Roaming\\npm\\node_modules\\alm\\src\\server\\workers\\lang\\docs\\docs.js:16:31)\n    at Child.RequesterResponder.processRequest (C:\\Users\\<username>\\AppData\\Roaming\\npm\\node_modules\\alm\\src\\server\\utils\\simpleWorker.js:95:60)\n    at process.<anonymous> (C:\\Users\\<username>\\AppData\\Roaming\\npm\\node_modules\\alm\\src\\server\\utils\\simpleWorker.js:323:23)\n    at emitTwo (events.js:106:13)',
  details: {} }
======================= STACK (getTopLevelModuleNames) ==========================
TypeError: Cannot read property 'kind' of undefined
    at transformModule (C:\Users\<username>\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\docs\transformers.js:323:18)
    at C:\Users\<username>\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\docs\transformers.js:55:27
    at visitEachNode (C:\Users\<username>\AppData\Roaming\npm\node_modules\alm\node_modules\typescript\lib\typescript.js:15008:30)
    at Object.forEachChild (C:\Users\<username>\AppData\Roaming\npm\node_modules\alm\node_modules\typescript\lib\typescript.js:15182:24)
    at getSignificantSubItems (C:\Users\<username>\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\docs\transformers.js:34:8)
    at Object.transformSourceFile (C:\Users\<username>\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\docs\transformers.js:21:20)
    at Object.getTopLevelModuleNames (C:\Users\<username>\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\docs\docs.js:16:31)
    at Child.RequesterResponder.processRequest (C:\Users\<username>\AppData\Roaming\npm\node_modules\alm\src\server\utils\simpleWorker.js:95:60)
    at process.<anonymous> (C:\Users\<username>\AppData\Roaming\npm\node_modules\alm\src\server\utils\simpleWorker.js:323:23)
    at emitTwo (events.js:106:13)
```

**Comment by basarat** [comment]
Will fix when we work on https://github.com/alm-tools/alm/issues/479 

FWIW I personally do not use tslint much :rose:
