### ISSUE TITLE
errors in analysis of node_modules

### ISSUE THREAD

**Issue by ki2ga** [alm-tools/alm#564]
Is there a way to exclude node_modules from the analysis?
I am getting a lot of errors coming from the node_modules folder which resides inside my project.
Moreover alm reports the below errors in the terminal and restarts fileListingWorker infinitely. There is no problem with disk space as you may think looking at ENOSPC error. The problems started after installing core-js npm package.

Version: 2.36.4, TypeScript version: 2.4.0-dev.20170515
DASHBOARD: (Please open in chrome) http://localhost:4444
TSCONFIG: All Good! /home/raf/workspace/training/tsconfig.json
[LINT] No tslint configuration found.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/raf/workspace/training/node_modules/serve-index/public/icons/page_white_powerpoint.png ENOSPC
    at exports._errnoException (util.js:1018:11)
    at FSWatcher.start (fs.js:1443:19)
    at Object.fs.watch (fs.js:1470:11)
    at createFsWatchInstance (/usr/local/lib/node_modules/alm/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/usr/local/lib/node_modules/alm/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/usr/local/lib/node_modules/alm/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/usr/local/lib/node_modules/alm/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/usr/local/lib/node_modules/alm/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:123:15)
fileListingWorker worker restarting. Don't know why it stopped with code: 1
[TSC] Started Initial Error Analysis: /home/raf/workspace/training/tsconfig.json
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/raf/workspace/training/node_modules/rxjs/add/operator/exhaust.js.map ENOSPC
    at exports._errnoException (util.js:1018:11)
    at FSWatcher.start (fs.js:1443:19)
    at Object.fs.watch (fs.js:1470:11)
    at createFsWatchInstance (/usr/local/lib/node_modules/alm/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/usr/local/lib/node_modules/alm/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/usr/local/lib/node_modules/alm/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/usr/local/lib/node_modules/alm/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/usr/local/lib/node_modules/alm/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:123:15)
fileListingWorker worker restarting. Don't know why it stopped with code: 1
[TSC] Error Analysis Duration: 3s
[TSC] FileCount: 4  Errors: 1
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/raf/workspace/training/node_modules/rxjs/add/operator/skipUntil.js.map ENOSPC
    at exports._errnoException (util.js:1018:11)
    at FSWatcher.start (fs.js:1443:19)
    at Object.fs.watch (fs.js:1470:11)
    at createFsWatchInstance (/usr/local/lib/node_modules/alm/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/usr/local/lib/node_modules/alm/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/usr/local/lib/node_modules/alm/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/usr/local/lib/node_modules/alm/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/usr/local/lib/node_modules/alm/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:123:15)
fileListingWorker worker restarting. Don't know why it stopped with code: 1

**Comment by basarat** [comment]
> Is there a way to exclude node_modules from the analysis?

Not yet. 

Leaving open to address other issues pointed out :rose:
