### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by no23reason** [alm-tools/alm#567]
While trying to install using `npm` the following is written on my screen:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\REDACTED\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'alm' ]
2 info using npm@5.3.0
3 info using node@v6.10.3
4 verbose npm-session 8b3116cb526cf8f9
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/alm 931ms
8 silly pacote tag manifest for alm@latest fetched in 996ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule alm@2.37.1 checking installable status
14 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/basic-auth-connect 239ms
15 silly pacote range manifest for basic-auth-connect@^1.0.0 fetched in 242ms
16 silly resolveWithNewModule basic-auth-connect@1.0.0 checking installable status
17 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/cookie-parser 343ms
18 silly pacote range manifest for cookie-parser@^1.3.5 fetched in 347ms
19 silly resolveWithNewModule cookie-parser@1.4.3 checking installable status
20 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/chalk 365ms
21 silly pacote range manifest for chalk@^1.1.3 fetched in 370ms
22 silly resolveWithNewModule chalk@1.1.3 checking installable status
23 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/deep-equal 389ms
24 silly pacote range manifest for deep-equal@^1.0.1 fetched in 397ms
25 silly resolveWithNewModule deep-equal@1.0.1 checking installable status
26 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/editorconfig 422ms
27 silly pacote range manifest for editorconfig@^0.13.2 fetched in 435ms
28 silly resolveWithNewModule editorconfig@0.13.2 checking installable status
29 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/escape-html 441ms
30 silly pacote range manifest for escape-html@^1.0.3 fetched in 451ms
31 silly resolveWithNewModule escape-html@1.0.3 checking installable status
32 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/glob 222ms
33 silly pacote range manifest for glob@^7.0.5 fetched in 228ms
34 silly resolveWithNewModule glob@7.1.2 checking installable status
35 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/chokidar 477ms
36 silly pacote version manifest for chokidar@1.6.1 fetched in 482ms
37 silly resolveWithNewModule chokidar@1.6.1 checking installable status
38 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/minimist 184ms
39 silly pacote range manifest for minimist@^1.2.0 fetched in 194ms
40 silly resolveWithNewModule minimist@1.2.0 checking installable status
41 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/fuzzaldrin 560ms
42 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/mkdirp 197ms
43 silly pacote range manifest for fuzzaldrin@^2.1.0 fetched in 566ms
44 silly resolveWithNewModule fuzzaldrin@2.1.0 checking installable status
45 silly pacote range manifest for mkdirp@^0.5.1 fetched in 201ms
46 silly resolveWithNewModule mkdirp@0.5.1 checking installable status
47 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/monaco-css 165ms
48 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/express 617ms
49 silly pacote version manifest for monaco-css@1.3.0 fetched in 197ms
50 silly resolveWithNewModule monaco-css@1.3.0 checking installable status
51 silly pacote version manifest for express@4.13.0 fetched in 651ms
52 silly resolveWithNewModule express@4.13.0 checking installable status
53 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/byots 684ms
54 silly pacote version manifest for byots@2.5.0-dev.20170626.4.12 fetched in 705ms
55 silly resolveWithNewModule byots@2.5.0-dev.20170626.4.12 checking installable status
56 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/multimatch 225ms
57 silly pacote range manifest for multimatch@^2.1.0 fetched in 235ms
58 silly resolveWithNewModule multimatch@2.1.0 checking installable status
59 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/monaco-languages 264ms
60 silly pacote version manifest for monaco-languages@0.7.0 fetched in 305ms
61 silly resolveWithNewModule monaco-languages@0.7.0 checking installable status
62 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/mv 234ms
63 silly pacote range manifest for mv@^2.1.1 fetched in 240ms
64 silly resolveWithNewModule mv@2.1.1 checking installable status
65 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/ncp 262ms
66 silly pacote range manifest for ncp@^2.0.0 fetched in 265ms
67 silly resolveWithNewModule ncp@2.0.0 checking installable status
68 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/open 193ms
69 silly pacote version manifest for open@0.0.5 fetched in 195ms
70 silly resolveWithNewModule open@0.0.5 checking installable status
71 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/node-fetch 282ms
72 silly pacote version manifest for node-fetch@1.6.3 fetched in 295ms
73 silly resolveWithNewModule node-fetch@1.6.3 checking installable status
74 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/resolve 174ms
75 silly pacote range manifest for resolve@^1.2.0 fetched in 179ms
76 silly resolveWithNewModule resolve@1.3.3 checking installable status
77 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/ora 235ms
78 silly pacote range manifest for ora@^0.2.0 fetched in 244ms
79 silly resolveWithNewModule ora@0.2.3 checking installable status
80 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/mocha 519ms
81 silly pacote version manifest for mocha@3.4.2 fetched in 550ms
82 silly resolveWithNewModule mocha@3.4.2 checking installable status
83 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/rimraf 254ms
84 silly pacote range manifest for rimraf@^2.4.2 fetched in 259ms
85 silly resolveWithNewModule rimraf@2.6.1 checking installable status
86 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/source-map-support 202ms
87 silly pacote version manifest for source-map-support@0.4.3 fetched in 204ms
88 silly resolveWithNewModule source-map-support@0.4.3 checking installable status
89 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/update-notifier 170ms
90 silly pacote version manifest for update-notifier@1.0.2 fetched in 173ms
91 silly resolveWithNewModule update-notifier@1.0.2 checking installable status
92 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/ts-node 229ms
93 silly pacote version manifest for ts-node@3.1.0 fetched in 233ms
94 silly resolveWithNewModule ts-node@3.1.0 checking installable status
95 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/ts-loader 346ms
96 silly pacote version manifest for ts-loader@2.0.0 fetched in 350ms
97 silly resolveWithNewModule ts-loader@2.0.0 checking installable status
98 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/tslint 377ms
99 silly pacote version manifest for tslint@5.0.0-dev.0 fetched in 384ms
100 silly resolveWithNewModule tslint@5.0.0-dev.0 checking installable status
101 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/socket.io 744ms
102 silly pacote range manifest for socket.io@^1.3.6 fetched in 759ms
103 silly resolveWithNewModule socket.io@1.7.4 checking installable status
104 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/webpack 938ms
105 silly pacote range manifest for webpack@^1.11.0 fetched in 993ms
106 silly resolveWithNewModule webpack@1.15.0 checking installable status
107 http fetch GET 200 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/typescript 1502ms
108 silly pacote version manifest for typescript@2.5.0-dev.20170627 fetched in 1531ms
109 silly resolveWithNewModule typescript@2.5.0-dev.20170627 checking installable status
110 http fetch GET 500 https://vzp.pkgs.visualstudio.com/_packaging/evzpcommonnpm/npm/registry/monaco 70951ms attempt #3
111 silly fetchPackageMetaData error for monaco@1.201701230409.0 500 Internal Server Error: monaco@1.201701230409.0
112 verbose stack Error: 500 Internal Server Error: monaco@1.201701230409.0
112 verbose stack     at fetch.then.res (C:\Users\REDACTED\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:41:19)
112 verbose stack     at tryCatcher (C:\Users\REDACTED\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
112 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\REDACTED\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
112 verbose stack     at Promise._settlePromise (C:\Users\REDACTED\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
112 verbose stack     at Promise._settlePromise0 (C:\Users\REDACTED\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
112 verbose stack     at Promise._settlePromises (C:\Users\REDACTED\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
112 verbose stack     at Async._drainQueue (C:\Users\REDACTED\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
112 verbose stack     at Async._drainQueues (C:\Users\REDACTED\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
112 verbose stack     at Immediate.Async.drainQueues (C:\Users\REDACTED\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
112 verbose stack     at runCallback (timers.js:672:20)
112 verbose stack     at tryOnImmediate (timers.js:645:5)
112 verbose stack     at processImmediate [as _immediateCallback] (timers.js:617:5)
113 verbose cwd C:\Projects\Idm\src\Vzp.Idm.Web.Admin.SpaUI
114 verbose Windows_NT 10.0.15063
115 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\REDACTED\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "alm"
116 verbose node v6.10.3
117 verbose npm  v5.3.0
118 error code E500
119 error 500 Internal Server Error: monaco@1.201701230409.0
120 verbose exit [ 1, true ]
```

**Comment by basarat** [comment]
> verbose stack Error: 500 Internal Server Error: monaco@1.201701230409.0

Please retry. Most likely NPM server error and nothing to do with us :rose:
