### ISSUE TITLE
Single Typescript file cannot be processed by ALM

### ISSUE THREAD

**Issue by hoegge** [alm-tools/alm#576]
I have a .ts file (`ShellDesktop.ts`) in my project that I noticed did not show any linting or highlighting. Looking at the terminal I got the error messages listed below. I made an exact file copy called `test.ts` and then it worked fine, and if I just rename the file it also works fine. I wonder how the filename can influence the outcome - can it clash with anything in the tool chain? Is the filename of any ts file of importance? (I use - for now - namespaces and not external modules in the project)

```
{ error: 'A query *that needs an active project* was made when there is no active project for given filePath',
  filePath: 'c:/Users/mhpedersen/Dropbox/Development/client MHP/webShell/Shell/ShellDesktop.ts',
  isThereAnActiveProject: true,
  filePathsCount: 21 }
{ method: 'quickInfo',
  message: 'A query *that needs an active project* was made when there is no active project for given filePath',
  stack: 'Error: A query *that needs an active project* was made when there is no active project for given filePath\n    at ifCurrentOrErrorOut (C:\\Users\\mhpedersen\\AppData\\Roaming\\npm\\node_modules\\alm\\src\\server\\workers\\lang\\activeProject.js:155:19)\n    at Object.quickInfo (C:\\Users\\mhpedersen\\AppData\\Roaming\\npm\\node_modules\\alm\\src\\server\\workers\\lang\\projectService.js:118:19)\n    at Child.RequesterResponder.processRequest (C:\\Users\\mhpedersen\\AppData\\Roaming\\npm\\node_modules\\alm\\src\\server\\utils\\simpleWorker.js:95:60)\n    at process.<anonymous> (C:\\Users\\mhpedersen\\AppData\\Roaming\\npm\\node_modules\\alm\\src\\server\\utils\\simpleWorker.js:323:23)\n    at emitTwo (events.js:106:13)\n    at process.emit (events.js:191:7)\n    at process.nextTick (internal/child_process.js:758:12)\n    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickCallback (internal/process/next_tick.js:104:9)',
  details: {} }
======================= STACK (quickInfo) ==========================
Error: A query *that needs an active project* was made when there is no active project for given filePath
    at ifCurrentOrErrorOut (C:\Users\mhpedersen\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\activeProject.js:155:19)
    at Object.quickInfo (C:\Users\mhpedersen\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\projectService.js:118:19)
    at Child.RequesterResponder.processRequest (C:\Users\mhpedersen\AppData\Roaming\npm\node_modules\alm\src\server\utils\simpleWorker.js:95:60)
    at process.<anonymous> (C:\Users\mhpedersen\AppData\Roaming\npm\node_modules\alm\src\server\utils\simpleWorker.js:323:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:758:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
{ error: 'A query *that needs an active project* was made when there is no active project for given filePath',
  filePath: 'c:/Users/mhpedersen/Dropbox/Development/client MHP/webShell/Shell/ShellDesktop.ts',
  isThereAnActiveProject: true,
  filePathsCount: 21 }
{ method: 'getQuickFixes',
  message: 'A query *that needs an active project* was made when there is no active project for given filePath',
  stack: 'Error: A query *that needs an active project* was made when there is no active project for given filePath\n    at ifCurrentOrErrorOut (C:\\Users\\mhpedersen\\AppData\\Roaming\\npm\\node_modules\\alm\\src\\server\\workers\\lang\\activeProject.js:155:19)\n    at Object.getQuickFixes (C:\\Users\\mhpedersen\\AppData\\Roaming\\npm\\node_modules\\alm\\src\\server\\workers\\lang\\projectService.js:503:19)\n    at Child.RequesterResponder.processRequest (C:\\Users\\mhpedersen\\AppData\\Roaming\\npm\\node_modules\\alm\\src\\server\\utils\\simpleWorker.js:95:60)\n    at process.<anonymous> (C:\\Users\\mhpedersen\\AppData\\Roaming\\npm\\node_modules\\alm\\src\\server\\utils\\simpleWorker.js:323:23)\n    at emitTwo (events.js:106:13)\n    at process.emit (events.js:191:7)\n    at process.nextTick (internal/child_process.js:758:12)\n    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickCallback (internal/process/next_tick.js:104:9)',
  details: {} }
======================= STACK (getQuickFixes) ==========================
Error: A query *that needs an active project* was made when there is no active project for given filePath
    at ifCurrentOrErrorOut (C:\Users\mhpedersen\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\activeProject.js:155:19)
    at Object.getQuickFixes (C:\Users\mhpedersen\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\projectService.js:503:19)
    at Child.RequesterResponder.processRequest (C:\Users\mhpedersen\AppData\Roaming\npm\node_modules\alm\src\server\utils\simpleWorker.js:95:60)
    at process.<anonymous> (C:\Users\mhpedersen\AppData\Roaming\npm\node_modules\alm\src\server\utils\simpleWorker.js:323:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:758:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
{ error: 'A query *that needs an active project* was made when there is no active project for given filePath',
  filePath: 'c:/Users/mhpedersen/Dropbox/Development/client MHP/webShell/Shell/ShellDesktop.ts',
  isThereAnActiveProject: true,
  filePathsCount: 21 }
{ method: 'quickInfo',
  message: 'A query *that needs an active project* was made when there is no active project for given filePath',
  stack: 'Error: A query *that needs an active project* was made when there is no active project for given filePath\n    at ifCurrentOrErrorOut (C:\\Users\\mhpedersen\\AppData\\Roaming\\npm\\node_modules\\alm\\src\\server\\workers\\lang\\activeProject.js:155:19)\n    at Object.quickInfo (C:\\Users\\mhpedersen\\AppData\\Roaming\\npm\\node_modules\\alm\\src\\server\\workers\\lang\\projectService.js:118:19)\n    at Child.RequesterResponder.processRequest (C:\\Users\\mhpedersen\\AppData\\Roaming\\npm\\node_modules\\alm\\src\\server\\utils\\simpleWorker.js:95:60)\n    at process.<anonymous> (C:\\Users\\mhpedersen\\AppData\\Roaming\\npm\\node_modules\\alm\\src\\server\\utils\\simpleWorker.js:323:23)\n    at emitTwo (events.js:106:13)\n    at process.emit (events.js:191:7)\n    at process.nextTick (internal/child_process.js:758:12)\n    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickCallback (internal/process/next_tick.js:104:9)',
  details: {} }
======================= STACK (quickInfo) ==========================
Error: A query *that needs an active project* was made when there is no active project for given filePath
    at ifCurrentOrErrorOut (C:\Users\mhpedersen\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\activeProject.js:155:19)
    at Object.quickInfo (C:\Users\mhpedersen\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\projectService.js:118:19)
    at Child.RequesterResponder.processRequest (C:\Users\mhpedersen\AppData\Roaming\npm\node_modules\alm\src\server\utils\simpleWorker.js:95:60)
    at process.<anonymous> (C:\Users\mhpedersen\AppData\Roaming\npm\node_modules\alm\src\server\utils\simpleWorker.js:323:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:758:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by basarat** [comment]
The error is just diagnostics and can be ignored. 

Why it happens: 
* The frontend (ui) thinks the file is in the currently active TypeScript project
* The backend (server) *knows* it is not. 

Such sync errors can happen due to various timing issues. But they do resolve themselves between file renames, git branch hops, npm installs etc. Rename back to `ShellDesktop.ts` and you will be fine :rose:

**Comment by hoegge** [comment]
Ok - I'll try that. The file IS in the currently active TypeScript project, though. Does that make a difference?

**Comment by basarat** [comment]
> Does that make a difference?

nope.
