### ISSUE TITLE
Localhost crashes on my VirtualBox Windows 10 Instance after adding a file

### ISSUE THREAD

**Issue by samnau** [alm-tools/alm#580]
I was trying ALM out for the first time on my Windows 10 VM. I did the basic steps for a new project. I created a folder. I ran `alm -i` on that folder and then booted up ALM `alm -o`. That worked fine. But as soon as I create a new file, the localhost process stops running due to an error:

```
Error: spawn git ENOENT
  at _errnoException (util.js:1024:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js
  at onErrorNT (internal/child_process.js:372:16)
  at _combinedTickCallback (internal/process/next_tick.js:138:11)
  at process._tickCallback (internal/process/next_tick.js:180:9)
```
I only tried to make a single new `.ts` file. Restarting the program every time after that has the same result. Oddly, I do not have this issue on my Macbook.

**Comment by basarat** [comment]
It might just be easier to make git a requirement and mention it here : https://alm-tools.gitbooks.io/alm/content/quickstart.html

That said, git is only run in an external process so should not crash the server : https://github.com/alm-tools/alm/blob/f45b858f784ea4615c1df93ab55712ca2155c060/src/server/workers/external/gitService.ts#L13

So are you sure the server crashes? or is it just an annoying log message. Thanks :rose:
