### ISSUE TITLE
Crash and continue on startup

### ISSUE THREAD

**Issue by cakenggt** [alm-tools/alm#582]
The editor still works after this error is thrown in the console.

```
======================= STACK (getJSOutputStatus) ==========================
TypeError: Cannot read property 'name' of undefined
    at beginCatchBlock (/Users/alec/.nvm/versions/node/v8.8.1/lib/node_modules/alm/node_modules/typescript/lib/typescript.js:59831:51)
    at transformAndEmitTryStatement (/Users/alec/.nvm/versions/node/v8.8.1/lib/node_modules/alm/node_modules/typescript/lib/typescript.js:59643:21)
    at transformAndEmitStatementWorker (/Users/alec/.nvm/versions/node/v8.8.1/lib/node_modules/alm/node_modules/typescript/lib/typescript.js:59094:28)
    at transformAndEmitStatement (/Users/alec/.nvm/versions/node/v8.8.1/lib/node_modules/alm/node_modules/typescript/lib/typescript.js:59060:13)
    at transformAndEmitStatements (/Users/alec/.nvm/versions/node/v8.8.1/lib/node_modules/alm/node_modules/typescript/lib/typescript.js:59044:17)
    at transformGeneratorFunctionBody (/Users/alec/.nvm/versions/node/v8.8.1/lib/node_modules/alm/node_modules/typescript/lib/typescript.js:58580:13)
    at visitFunctionExpression (/Users/alec/.nvm/versions/node/v8.8.1/lib/node_modules/alm/node_modules/typescript/lib/typescript.js:58510:37)
    at visitGenerator (/Users/alec/.nvm/versions/node/v8.8.1/lib/node_modules/alm/node_modules/typescript/lib/typescript.js:58450:28)
    at visitor (/Users/alec/.nvm/versions/node/v8.8.1/lib/node_modules/alm/node_modules/typescript/lib/typescript.js:58347:24)
    at visitNodes (/Users/alec/.nvm/versions/node/v8.8.1/lib/node_modules/alm/node_modules/typescript/lib/typescript.js:49100:48)
```

**Comment by basarat** [comment]
> TypeError: Cannot read property 'name' of undefined

TypeScript crashes sometimes. I just log it out on the console and then restart the compiler / language service so no biggie. TypeScript team finds / fixes these on their own :rose:
