### ISSUE TITLE
Error after installing alm

### ISSUE THREAD

**Issue by avielfedida** [alm-tools/alm#68]
After installed alm(got node v 5.3.0 + chrom 49.0.2623.110 m on windows 10), when I try to start it I get:
```
DASHBOARD: http://localhost:4444
C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\core\tsconfig.js:131
        toExpand = toExpand.concat(projectSpec.exclude.map(function (x) { return ("!./" + x); })); // as it is (for files)
                           ^

TypeError: Cannot read property 'concat' of undefined
    at Object.getProjectSync (C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\core\tsconfig.js:131:28)
    at Object.getProjectDataLoaded (C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server\disk\projectDataLoader.js:7:31)
    at C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\projectServiceMaster.js:53:45
    at C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\common\events.js:36:66
    at Array.forEach (native)
    at TypedEvent.emit (C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\common\events.js:36:29)
    at Object.start (C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server\disk\activeProjectConfig.js:63:55)
    at Object.started (C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server\serverStarted.js:9:25)
    at Server.<anonymous> (C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server.js:75:23)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1263:10)
    at nextTickCallbackWith1Arg (node.js:444:9)
    at process._tickCallback (node.js:366:17)
    at Function.Module.runMain (module.js:432:11)

C:\Users\avielfedida\Desktop\fedidapp>alm -h
DASHBOARD: http://:4444
C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\core\tsconfig.js:131
        toExpand = toExpand.concat(projectSpec.exclude.map(function (x) { return ("!./" + x); })); // as it is (for files)
                           ^

TypeError: Cannot read property 'concat' of undefined
    at Object.getProjectSync (C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\core\tsconfig.js:131:28)
    at Object.getProjectDataLoaded (C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server\disk\projectDataLoader.js:7:31)
    at C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\projectServiceMaster.js:53:45
    at C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\common\events.js:36:66
    at Array.forEach (native)
    at TypedEvent.emit (C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\common\events.js:36:29)
    at Object.start (C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server\disk\activeProjectConfig.js:63:55)
    at Object.started (C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server\serverStarted.js:9:25)
    at Server.<anonymous> (C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server.js:75:23)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1263:10)
    at nextTickCallbackWith1Arg (node.js:444:9)
    at process._tickCallback (node.js:366:17)
    at Function.Module.runMain (module.js:432:11)

C:\Users\avielfedida\Desktop\fedidapp>

C:\Users\avielfedida\Desktop\fedidapp>node -v
v5.3.0

C:\Users\avielfedida\Desktop\fedidapp>alm .
DASHBOARD: http://localhost:4444
C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\core\tsconfig.js:131
        toExpand = toExpand.concat(projectSpec.exclude.map(function (x) { return ("!./" + x); })); // as it is (for files)
                           ^

TypeError: Cannot read property 'concat' of undefined
    at Object.getProjectSync (C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\core\tsconfig.js:131:28)
    at Object.getProjectDataLoaded (C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server\disk\projectDataLoader.js:7:31)
    at C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server\workers\lang\projectServiceMaster.js:53:45
    at C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\common\events.js:36:66
    at Array.forEach (native)
    at TypedEvent.emit (C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\common\events.js:36:29)
    at Object.start (C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server\disk\activeProjectConfig.js:63:55)
    at Object.started (C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server\serverStarted.js:9:25)
    at Server.<anonymous> (C:\Users\avielfedida\AppData\Roaming\npm\node_modules\alm\src\server.js:75:23)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1263:10)
    at nextTickCallbackWith1Arg (node.js:444:9)
    at process._tickCallback (node.js:366:17)
    at Function.Module.runMain (module.js:432:11)
```

**Comment by basarat** [comment]
Please share the `tsconfig.json` :rose:

**Comment by avielfedida** [comment]
Sorry, here it is, what I past here is `tsconfig.json` the I also added the `tsconfig.js` [here](http://pastebin.com/0UyMt8w8):

```
{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "noEmitOnError": false,
    "rootDir": ".",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "sourceRoot": "",
    "inlineSourceMap": false,
    "inlineSources": false
  },
  "files": [
    "app/app.ts",
    "typings/**/* .ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false
}

```

**Comment by basarat** [comment]
The files property cannot be used in consjunction with exclude. More : https://www.typescriptlang.org/docs/handbook/tsconfig.json.html < Leaving this open as I'd like to show this error to the user if they have this misconfigured :rose:

 Also `files` cannot contains globs. If you want those you need to use `filesGlob`.

**Comment by basarat** [comment]
> Leaving this open as I'd like to show this error to the user if they have this misconfigured

On second thought closing for now as a user error :rose: Better validation work is in my private queue already :rose:

**Comment by basarat** [comment]
@avielfedida instead of crashing and :fire:ing alm will now report the error and watch the tsconfig.json for changes so that as soon as the tsconfig is valid it all just works https://github.com/alm-tools/alm/commit/0a4af975b76cb9aff68e5f15b3cb0915dce11474 

Release with `0.0.31` :rose:

**Comment by avielfedida** [comment]
@basarat Thank you, it sounds great !
